package migration

// NOTE Don't Modify this file

func AutoGenerated() {
	migrations = nil
	migration_2021_03_19T10_05_30Z_CreateModel_User()
	migration_2021_03_20T10_05_30Z_CreateModel_Role()
	// AutogenEndOfFile
}
