package permissionutils

const (
	PERMISSION_READ_ADMIN  = "PERMISSION_READ_ADMIN"
	PERMISSION_WRITE_ADMIN = "PERMISSION_WRITE_ADMIN"

	PERMISSION_READ_ACCOUNT  = "PERMISSION_READ_ACCOUNT"
	PERMISSION_WRITE_ACCOUNT = "PERMISSION_WRITE_ACCOUNT"

	PERMISSION_READ_USER  = "PERMISSION_READ_USER"
	PERMISSION_WRITE_USER = "PERMISSION_WRITE_USER"
)

var (
	ROLE_DEFAULT_ADMIN = "admin"
)
